# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: goldencodesolutions
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: upwork-job-notifier
# "service" is the name of this project. This will also be added to your AWS resource names.
service: upwork-job-notifier

custom:
  projectTag: upworkJobNotifier
  webpack:
    webpackConfig: '../webpack.config.js'
    includeModules: true

provider:
  name: aws
  runtime: nodejs20.x
  tags:
    project: ${self:custom.projectTag}

  # deploymentBucket: This line can be removed if you don't want to use a custom bucket and prefer to let Serverless create the bucket automatically.
  deploymentBucket:
    name: upworkjobnotifierbucket
    tags:
      project: ${self:custom.projectTag}

  environment:
    EMAIL_TO: ${env:EMAIL_TO}
    EMAIL_FROM: ${env:EMAIL_FROM}
    EMAIL_FROM_NAME: ${env:EMAIL_FROM_NAME}
    EMAIL_SENDGRID_API_KEY: ${env:EMAIL_SENDGRID_API_KEY}

package:
  individually: true
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-webpack

build:
  esbuild: false

functions:
  jobsNotifierHandler:
    handler: handler.jobsNotifierHandler
    events:
      - schedule: 
          # Invoke Lambda function every certain time
          rate: rate(30 minutes)