# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: goldencodesolutions
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: upwork-job-notifier
# "service" is the name of this project. This will also be added to your AWS resource names.
service: upwork-job-notifier

provider:
  name: aws
  runtime: nodejs20.x
  tags:
    project: upworkJobNotifier
  environment:
    EMAIL_TO: ${env:EMAIL_TO}
    EMAIL_FROM: ${env:EMAIL_FROM}
    EMAIL_FROM_NAME: ${env:EMAIL_FROM_NAME}
    EMAIL_SENDGRID_API_KEY: ${env:EMAIL_SENDGRID_API_KEY}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  jobsNotifierHandler:
    handler: handler.jobsNotifierHandler
    events:
      # Invoke Lambda function every minute
      - schedule: rate(30 minutes)